package cli

import (
	"fmt"

	"github.com/charmbracelet/huh"
	"github.com/mirakuta-dev/mirakuta/internal/preset"
)

// defaultVSCodeExtensions maps a language key to recommended VS Code extensions.
// Used only when the wizard generates a profile — hand-authored presets list
// extensions explicitly.
var defaultVSCodeExtensions = map[string][]string{
	"go":     {"golang.Go"},
	"node":   {"dbaeumer.vscode-eslint", "esbenp.prettier-vscode"},
	"python": {"ms-python.python"},
	"rust":   {"rust-lang.rust-analyzer"},
}

// runWizard collects the user's choices via an interactive form and returns
// a Preset that captures those choices. A nil error means the user confirmed
// installation.
func runWizard() (preset.Preset, bool, error) {
	var (
		languages []string
		editor    string
		terminals []string
		gitName   string
		gitEmail  string
		confirm   bool
	)

	form := huh.NewForm(
		huh.NewGroup(
			huh.NewMultiSelect[string]().
				Title("어떤 언어를 사용하시나요? (Space로 선택, Enter로 다음)").
				Options(
					huh.NewOption("Go", "go"),
					huh.NewOption("Node.js", "node"),
					huh.NewOption("Python", "python"),
					huh.NewOption("Rust", "rust"),
				).
				Value(&languages),
		),
		huh.NewGroup(
			huh.NewSelect[string]().
				Title("에디터는?").
				Options(
					huh.NewOption("VS Code", "vscode"),
					huh.NewOption("Neovim", "neovim"),
					huh.NewOption("IntelliJ", "intellij"),
				).
				Value(&editor),
		),
		huh.NewGroup(
			huh.NewMultiSelect[string]().
				Title("터미널은?").
				Options(
					huh.NewOption("Windows Terminal", "windows-terminal"),
					huh.NewOption("PowerShell 7", "pwsh"),
				).
				Value(&terminals),
		),
		huh.NewGroup(
			huh.NewInput().
				Title("Git user.name").
				Value(&gitName),
			huh.NewInput().
				Title("Git user.email").
				Value(&gitEmail),
		),
		huh.NewGroup(
			huh.NewConfirm().
				Title("이 구성으로 설치할까요?").
				Affirmative("설치").
				Negative("취소").
				Value(&confirm),
		),
	)

	if err := form.Run(); err != nil {
		return preset.Preset{}, false, fmt.Errorf("wizard: %w", err)
	}

	p := preset.Preset{
		Name:        "custom",
		Description: "Generated by mirakuta install wizard",
		Languages:   languages,
		Terminals:   terminals,
		Git:         preset.Git{Name: gitName, Email: gitEmail},
	}
	if editor != "" {
		exts := []string{}
		if editor == "vscode" {
			for _, lang := range languages {
				exts = append(exts, defaultVSCodeExtensions[lang]...)
			}
		}
		p.Editors = []preset.Editor{{ID: editor, Extensions: exts}}
	}

	return p, confirm, nil
}
